export const fetchAuthcodeForResetPasswordActionTypes = {
  REQUEST: 'FETCH_AUTHCODE_FOR_RESET_PASSWORD_REQUEST',
  SUCCESS: 'FETCH_AUTHCODE_FOR_RESET_PASSWORD_SUCCESS',
  FAILURE: 'FETCH_AUTHCODE_FOR_RESET_PASSWORD_FAILURE',
};
